# Generated by Django 5.0.2 on 2024-03-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Books',
        ),
    ]
